name: Run main.py every morning (Docker)

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 0:00 UTC every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t selkouutiset-bot .

      - name: Run main.py in Docker
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          docker run --rm \
            -e DISCORD_BOT_TOKEN \
            -e DISCORD_CHANNEL_ID \
            -e OPENAI_API_KEY \
            -v ${{ github.workspace }}/translated_news:/app/translated_news \
            selkouutiset-bot

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./translated_news
          publish_branch: gh-pages